### ISSUE TITLE
2.2 Planejamento das Fases e/ou Iterações do Projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArtPlace#10]
- [x] existem 4 missões, e não 3, como está no planejamento
- [x] não apresentam produtos a serem entregues nas sprints, e sim, atividades. ajustem todos.

![image](https://github.com/mdsreq-fga-unb/2023.2-ArtPalce/assets/68402547/ee53649f-0c53-4991-b1b0-81fb92276c4a)

**Comment by NyndoND** [comment]
Resolvido pelo PR linkado https://github.com/mdsreq-fga-unb/2023.2-ArtPlace/pull/24
