### ISSUE TITLE
2.2 Planejamento das Fases e/ou Iterações do Projeto - SPRINTS

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArtPlace#11]
- [x] sprints com dias variados?!

![image](https://github.com/mdsreq-fga-unb/2023.2-ArtPalce/assets/68402547/0a169a46-edac-43a9-a019-a7f1ce7bf0dd)

**Comment by NyndoND** [comment]
Resolvido pelo PR linkado https://github.com/mdsreq-fga-unb/2023.2-ArtPlace/pull/24
