### ISSUE TITLE
2.3 Matriz de Comunicação

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArtPlace#12]
- [x] Quais são os PRODUTOS A SEREM GERADOS?!

![image](https://github.com/mdsreq-fga-unb/2023.2-ArtPalce/assets/68402547/4c14b059-5de0-4015-b89c-e0da5e56088f)

**Comment by rafa-kenji** [comment]
Resolvida no commit [https://github.com/mdsreq-fga-unb/2023.2-ArtPlace/commit/e93ae76ca8296df71c2cbeeb715a815838b4dc6f]
