### ISSUE TITLE
2.5 Critérios de Replanejamento

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArtPlace#14]
- [x] Listagem dos critérios ficou mal formatada dificultando a leitura.
- [x] Nenhuma relação entre RISCOS e CRITÉRIOS DE REPLANEJAMENTO? Ou seja, a incidência de um ou mais riscos identificados não levam a um replanejamento?

**Comment by NyndoND** [comment]
Issue concluída com base no PR linkado
