### ISSUE TITLE
Processo

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArtPlace#15]
- [x] imagens ilegíveis

**Comment by Muniz2811** [comment]
Resolvido nos commits: [ https://github.com/mdsreq-fga-unb/2023.2-ArtPlace/commit/8342188f988d4ba3f997832dc7b635e034e2755f,  https://github.com/mdsreq-fga-unb/2023.2-ArtPlace/commit/adca4e00de44ed9310eefbded534d964246864c4 ]
