### ISSUE TITLE
Tabela de atividades

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArtPlace#16]
- [x] quais são as entregas?
- [x] apenas brainstorming para elicitação e descoberta?
- [x] apenas brainstorming para Análise e consenso?
- [x] no backlog só haverá história?
- [x] Verificação e validação: qual o conceito de análise de requisitos?

**_Para a disciplina de REQ, o conjunto de métodos a serem abordados está bastante incompleto._**

![image](https://github.com/mdsreq-fga-unb/2023.2-ArtPalce/assets/68402547/795be5cc-350a-4743-8962-30b83d404896)

**Comment by Muniz2811** [comment]
Resolvido no commit: [ https://github.com/mdsreq-fga-unb/2023.2-ArtPlace/commit/8342188f988d4ba3f997832dc7b635e034e2755f ]
