### ISSUE TITLE
Materiais

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArtPlace#17]
desconsiderado, pois foi postado fora do GitPages.

![image](https://github.com/mdsreq-fga-unb/2023.2-ArtPalce/assets/68402547/4b6a52f6-77de-4a83-9e61-a48ba8088d33)

![image](https://github.com/mdsreq-fga-unb/2023.2-ArtPalce/assets/68402547/62b31bd5-c159-4855-b7dd-a5a10cd27f49)

**Comment by rafa-kenji** [comment]
Resolvida no commit [https://github.com/mdsreq-fga-unb/2023.2-ArtPlace/commit/9f940baea21ff705e36a3b2004b7348be4a2aeb6]
