### ISSUE TITLE
Validação MVP

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArtPlace#25]
> QUAL, DE FATO,  O VALOR DE NEGÓCIO DO PRODUTO? O MVP ESTÁ CHEIO DE US 'ADMINISTRATIVAS': LOGIN, CADASTRO NA PLATAFORMA, ALTERAÇÃO DE PERFIL, FOTO.

> NÃO SÃO US
- Eu, como usuário, quero saber sobre as políticas de privacidade da plataforma, para saber meus direitos e deveres na comunidade. 
- Eu, como artista, quero saber sobre as políticas privadas, para fazer as publicações dos meus produtos sem ferir uma regra da plataforma. 
 

> SÃO DOIS CADASTROS DIFERENTES?
- Eu, como usuário, quero me cadastrar na plataforma, para ter acesso aos produtos que estão disponíveis.
- Eu, como artista quero me cadastrar na plataforma, para poder divulgar meus produtos no site

**Comment by NyndoND** [comment]
Aguardando revisão do Comandante Estelar para fechar a issue.
