### ISSUE TITLE
visão geral produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArtPlace#5]
deve ser feita uma revisão geral de ortografia e gramática. textos e imagens.

**Comment by pkbceira03** [comment]
Fizemos as correções ortográficas e gramaticais nos commits (https://github.com/mdsreq-fga-unb/2023.2-ArtPlace/commit/18b41429744f0946cc946f5203a7225f228f5a8c) e (https://github.com/mdsreq-fga-unb/2023.2-ArtPlace/commit/7fb6b4ad3cf209322df2e33d865ad6284cf74d22)
