### ISSUE TITLE
1.2 Declaração de Posição do Produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArtPlace#6]
**Que cliente?**

'O ArtPlace será desenvolvido para o cliente tendo em vista a falta de exclusividade nas plataformas atuais, e ele se propõe a ser uma solução web com o intuito de exibir os produtos artesanais feitos pelo cliente contando também com áreas de exibição e interação entre os possíveis clientes e artistas do site. O produto contará com a possibilidade de novos artistas que acharem a solução útil, se cadastrarem e também exibirem seus produtos a fim de criar uma comunidade.'

**Comment by pkbceira03** [comment]
Revolvemos na commit (https://github.com/mdsreq-fga-unb/2023.2-ArtPlace/commit/18b41429744f0946cc946f5203a7225f228f5a8c)
