### ISSUE TITLE
2.1 Organização do Projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArtPlace#9]
- [x] Dono do Produto: Renann, Cabeceira e Fause **_(NÃO. O DONO DO PRODUTO É O CLIENTE, NÃO UM MEMBRO DA EQUIPE)_**
- [x] O prof da disciplina tb é cliente
- [x] vocês estão em uma disciplina de REQ, onde estão os responsáveis por ela?
- [x] Analista de Qualidade: Garantir a qualidade do produto, garantir o cumprimento do **_conceito de pronto_**, realizar inspeções de código. _**Quem garante a qualidade dos requisitos?!?!?**_ e o **_conceito de preparado?!_**

![image](https://github.com/mdsreq-fga-unb/2023.2-ArtPalce/assets/68402547/af7fef4e-2d54-4e1c-ac16-56196911bf51)

**Comment by pkbceira03** [comment]
Arrumado no commit (https://github.com/mdsreq-fga-unb/2023.2-ArtPlace/commit/4a9681e63261ccf6b9f183c6628572a227d7f84f)
